version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels: [maintenance]
    groups:
      actions:
        patterns: ['*']

  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
    labels: [maintenance]
    groups:
      minor-and-patch:
        update-types: ["minor", "patch"]
      major-updates:
        update-types: ["major"]
